<?php

function sum_menu() {
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sum_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['success']=array(
        'title' => 'Success',
        'page callback' => 'sum_success',
        'access callback'=> TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function sum_form() {
    $form['left_number'] = array(
        '#title' => 'Left number',
        '#type' => 'textfield',
        '#description' => t('Please enter your starting number.'),
        '#element_validate' => array('element_validate_number', 'element_validate_kelly'),
        '#required' => TRUE,
    );

    $form['right_number'] = array(
        '#title' => 'Right number',
        '#type' => 'textfield',
        '#description' => t('Please enter a number to add to the starting number.'),
        '#element_validate' => array('element_validate_number', 'element_validate_kelly'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );

    return $form;
}

function sum_form_submit($form, &$form_state){
    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['first_number'] = $first_number;
    $_SESSION['second_number'] = $second_number;

    $form_state['redirect']='success';
}
function sum_success(){
    $first = $_SESSION['first_number'];
    $second = $_SESSION['second_number'];
    $sum = $first + $second;
    return 'You calculated a sum! ' . $first . ' + ' . $second . ' = ' . $sum;
}

function element_validate_kelly($validater){
    if($validater['#value'] > 50 || $validater['#value'] < -50){
        form_error($validater, t('Number must be less than 50 or greater than -50'));
    }


}
